### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MatthewNeie**
updating readme to main

### CODE REVIEW

**Review by singhalex — APPROVED** [review]

**Comment by belunatic** [comment]
@MatthewNeie I am not sure what is happening on the `Built with section` formatting issue!

**Comment by MatthewNeie** [comment]
> @MatthewNeie I am not sure what is happening on the `Built with section` formatting issue!

we can omit that for now, will make change

**Comment by MatthewNeie** [comment]
I would like to make expense group management, expense management, receipts, analytics, user interface summary sections in functionality. Should I just go ahead and write something and see if we want to keep the changes?

**Review by kristi-h — APPROVED** [review]

**Comment by MatthewNeie** [comment]
adding new deployment site

https://expensesplittermain.netlify.app/

**Review by ccespedes — APPROVED** [review]

**Pull request merged**
